swagger: '2.0'
info:
  title: AIRR Data Commons API
  version: 1.0.0
  contact:
    name: AIRR Community
    url: 'http://www.airr-community.org/'
    email: join@airr-community.org
  description: >
    Major Version 1 of the Adaptive Immune Receptor Repertoire (AIRR)
    data repository web service application programming interface (API).
basePath: /airr/v1

definitions:
  # list of repertoires
  repertoire_list:
    type: array
    items:
      $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/airr-schema.yaml#/Repertoire'

  # The response object /repertoire endpoint
  repertoire_response:
    type: object
    properties:
      Info:
        type: object
        description: Provides information about the API response
      Repertoire:
        $ref: '#/definitions/repertoire_list'

  # list of rearrangement annotations
  rearrangement_list:
    type: array
    items:
      $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/airr-schema.yaml#/Rearrangement'

  # The response object /rearrangement endpoint
  rearrangement_response:
    type: object
    properties:
      Info:
        type: object
        description: Provides information about the API response
      Rearrangement:
        $ref: '#/definitions/rearrangement_list'

  # error response
  error_response:
    type: object
    properties:
      message:
        type: string
        description: Detail about the error

schemes:
  - https
produces:
  - application/json
consumes:
  - application/x-www-form-urlencoded
  - application/json
tags:
  - name: info
    description: Service information
  - name: repertoires
    description: Queries for repertoires
  - name: rearrangements
    description: Queries for rearrangements

paths:
  /:
    x-swagger-router-controller: status
    get:
      description: |
        Service heartbeat.
      consumes:
        - application/octet-stream
      operationId: getStatus
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              result:
                type: string

  /info:
    x-swagger-router-controller: status
    get:
      description: |
        Service information.
      tags:
        - info
      consumes:
        - application/octet-stream
      operationId: getInfo
      responses:
        '200':
          description: |
            Success.
          schema:
            type: object
            properties:
              name:
                type: string
              version:
                type: string

  /swagger:
    x-swagger-pipe: swagger_raw

  /repertoire/{repertoire_id}:
    x-swagger-router-controller: repertoire
    get:
      description: >
        Returns a repertoire based upon its identifier.
      tags:
        - repertoires
      consumes:
        - application/x-www-form-urlencoded
        - application/json
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: repertoire_id
          in: path
          description: ID of repertoire to return
          required: true
          type: string
      operationId: getRepertoire
      responses:
        '200':
          description: |
            A successful call returns the repertoire data.
          schema:
            $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/airr-schema.yaml#/Repertoire'
        '400':
          description: Invalid repertoire ID supplied
        '404':
          description: Repertoire not found

  /repertoire:
    x-swagger-router-controller: repertoire
    post:
      description: >
        This query service returns metadata about repertoires.
      tags:
        - repertoires
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              filters:
                type: object
              format:
                type: string
              fields:
                type: array
                items:
                  type: string
              size:
                type: number
              from:
                type: number
      operationId: queryRepertoires
      responses:
        '200':
          description: >
            A successful call returns an array of repertoire metadata.
          schema:
            $ref: '#/definitions/repertoire_response'
        '400':
          description: Invalid request
          schema:
            $ref: '#/definitions/error_response'

  /rearrangement/{rearrangement_id}:
    x-swagger-router-controller: rearrangement
    get:
      description: >
        Returns a rearrangement based upon its identifier.
      tags:
        - rearrangements
      consumes:
        - application/x-www-form-urlencoded
        - application/json
        - application/octet-stream
      produces:
        - application/json
      parameters:
        - name: rearrangement_id
          in: path
          description: ID of rearrangement to return
          required: true
          type: string
      operationId: getRearrangement
      responses:
        '200':
          description: >
            A successful call returns the rearrangement annotation data.
          schema:
            $ref: 'https://raw.githubusercontent.com/airr-community/airr-standards/master/specs/airr-schema.yaml#/Rearrangement'
        '400':
          description: Invalid rearrangement ID supplied
        '404':
          description: Rearrangement not found

  /rearrangement:
    x-swagger-router-controller: rearrangement
    post:
      description: >
        This query service returns rearrangement annotation data.
      tags:
        - rearrangements
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              filters:
                type: object
              format:
                type: string
              fields:
                type: array
                items:
                  type: string
              size:
                type: number
              from:
                type: number
      operationId: queryRearrangements
      responses:
        '200':
          description: >
            A successful call returns an array of rearrangement annotation data.
          schema:
            $ref: '#/definitions/rearrangement_response'
